version: '3.8'

services:
  nginx:
    image: "nginx:inception"
    container_name: nginx
    build: ./requirements/nginx/.
    volumes:
      - /home/afanidi/data/nginx:/var/www/html 
      - /home/afanidi/data/nginx/logs:/var/log/nginx
    ports:
      - "443:443"
    networks:
      - inceptionNet
    env_file:
      - .env
    restart: always
    depends_on:
      - wordpress
    
  wordpress:
    image: "wordpress:inception"
    container_name: wordpress
    build: ./requirements/wordpress/.
    volumes:
      - /home/afanidi/data/wordpress:/var/www/html
      - /home/afanidi/data/php/logs:/var/log/php-fpm.log
    networks:
      - inceptionNet
    env_file:
      - .env
    restart: always
    depends_on:
      - mariadb

  mariadb:
    image: "mariadb:inception"
    container_name: mariadb
    build: ./requirements/mariadb/.
    volumes:
      - /home/afanidi/data/mariadb:/var/lib/mysql
      - /home/afanidi/data/mariadb/logs:/var/log/mysql
    networks:
      - inceptionNet
    env_file:
      - .env
    restart: always
  redis:
    image: "redis:inception"
    build: ./requirements/bonus/redis/.
    container_name: redis
    networks:
      - inceptionNet
    restart: always
    

#Custom network
networks:
  inceptionNet:
    driver: bridge
